# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(blank=True, default=b'Uncategorized', help_text=b'Category of training, eg. FEMA', max_length=120, null=True)),
                ('gamification_signals', models.CharField(blank=True, help_text=b'After training which Signals should be sent to gamification server?', max_length=250, null=True)),
                ('content_link', models.CharField(blank=True, help_text=b'Link to PDF/PPT/training or web page for training that will open in a new window', max_length=500, null=True)),
                ('quiz_data', jsonfield.fields.JSONField(blank=True, help_text=b'If user should be quized after, list of questions and answers and percent_complete if not 100%', null=True)),
                ('description', models.TextField(blank=True, help_text=b'Details to show potential student.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text=b'Last updated time/date')),
                ('private', models.BooleanField(default=False, help_text=b'Check to hide in public list')),
                ('primary_contact', models.ForeignKey(help_text=b'Contact for training.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users_completed', models.ManyToManyField(blank=True, help_text=b'Users that completed this training.', null=True, related_name='users_completed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
