# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'core', '0002_auto_20170331_1227'), (b'core', '0003_auto_20180401_1938'), (b'core', '0004_auto_20180406_1907'), (b'core', '0005_auto_20180407_2044'), (b'core', '0006_auto_20180407_2120')]

    dependencies = [
        ('training', '__first__'),
        ('workflow', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='editable_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.EditableMapLayer'),
        ),
        migrations.AddField(
            model_name='job',
            name='feature_types',
            field=models.ManyToManyField(blank=True, to=b'maps.FeatureType'),
        ),
        migrations.AddField(
            model_name='job',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Map'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_courses',
            field=models.ManyToManyField(blank=True, help_text=b'Courses that must be passed to open these cells', to=b'training.Training'),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to=b'auth.Group'),
        ),
        migrations.AddField(
            model_name='comment',
            name='aoi',
            field=models.ForeignKey(help_text=b'Associated AOI for comment', on_delete=django.db.models.deletion.CASCADE, to='core.AOI'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'User who made comment', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoitimer',
            name='aoi',
            field=models.ForeignKey(help_text=b'Workcell that was changed', on_delete=django.db.models.deletion.CASCADE, to='core.AOI'),
        ),
        migrations.AddField(
            model_name='aoitimer',
            name='user',
            field=models.ForeignKey(help_text=b'User who worked on workcell', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoi',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text=b'User assigned to work the workcell.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoi',
            name='assignee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aois', to='core.Job'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text=b'Users that actually reviewed this work.', null=True, related_name='aoi_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='aoi',
            options={'ordering': ['id'], 'permissions': (('assign_workcells', 'Assign Workcells'), ('certify_workcells', 'Certify Workcells')), 'verbose_name': 'Area of Interest', 'verbose_name_plural': 'Areas of Interest'},
        ),
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text=b'Workflow to be used for job', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text=b'Users that actually reviewed this work.', related_name='aoi_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='analysts',
            field=models.ManyToManyField(blank=True, related_name='analysts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text=b'User that will be able to take on jobs.', related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(blank=True, help_text=b'User that has admin rights to project.', related_name='project_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='status',
            field=models.CharField(default=b'Unassigned', max_length=15),
        ),
        migrations.AlterField(
            model_name='aoitimer',
            name='status',
            field=models.CharField(default=b'Unassigned', max_length=20),
        ),
    ]
