# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '__first__'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('maps', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='editable_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.EditableMapLayer'),
        ),
        migrations.AddField(
            model_name='job',
            name='feature_types',
            field=models.ManyToManyField(blank=True, null=True, to='maps.FeatureType'),
        ),
        migrations.AddField(
            model_name='job',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.Map'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.Project'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_courses',
            field=models.ManyToManyField(blank=True, help_text=b'Courses that must be passed to open these cells', null=True, to='training.Training'),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='comment',
            name='aoi',
            field=models.ForeignKey(help_text=b'Associated AOI for comment', on_delete=django.db.models.deletion.CASCADE, to='core.AOI'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text=b'User who made comment', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoitimer',
            name='aoi',
            field=models.ForeignKey(help_text=b'Workcell that was changed', on_delete=django.db.models.deletion.CASCADE, to='core.AOI'),
        ),
        migrations.AddField(
            model_name='aoitimer',
            name='user',
            field=models.ForeignKey(help_text=b'User who worked on workcell', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoi',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text=b'User assigned to work the workcell.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aoi',
            name='assignee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aois', to='core.Job'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text=b'Users that actually reviewed this work.', null=True, related_name='aoi_reviewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
