# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170331_1227_squashed_0006_auto_20180407_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contact_instructions', models.CharField(max_length=1024)),
                ('in_field', models.BooleanField()),
                ('last_seen', models.DateTimeField(null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
    ]
