# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-01 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        ('core', '0002_auto_20170331_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aoi',
            options={'ordering': ['id'], 'permissions': (('assign_workcells', 'Assign Workcells'), ('certify_workcells', 'Certify Workcells')), 'verbose_name': 'Area of Interest', 'verbose_name_plural': 'Areas of Interest'},
        ),
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text=b'Users that actually reviewed this work.', related_name='aoi_reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='analysts',
            field=models.ManyToManyField(blank=True, related_name='analysts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='feature_types',
            field=models.ManyToManyField(blank=True, to='maps.FeatureType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='progress',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_courses',
            field=models.ManyToManyField(blank=True, help_text=b'Courses that must be passed to open these cells', to='training.Training'),
        ),
        migrations.AlterField(
            model_name='job',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text=b'User that will be able to take on jobs.', related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(blank=True, help_text=b'User that has admin rights to project.', related_name='project_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
