# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-06 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180401_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text=b'Workflow to be used for job', null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
    ]
