# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-08 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180407_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoitimer',
            name='status',
            field=models.CharField(default=b'Unassigned', max_length=20),
        ),
    ]
