# Generated by Django 3.0.7 on 2020-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='type',
            field=models.CharField(choices=[('Object', 'Object'), ('Property', 'Property'), ('Relationship', 'Relationship')], default=('Object', 'Object'), max_length=30),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='url',
            field=models.CharField(help_text='Location of ontology', max_length=200),
        ),
        migrations.AlterField(
            model_name='term',
            name='identifier',
            field=models.CharField(help_text='IRI Identifier', max_length=200),
        ),
    ]
