# Generated by Django 3.0.5 on 2020-07-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='url',
            field=models.CharField(help_text='Location of ontology', max_length=200),
        ),
        migrations.AlterField(
            model_name='term',
            name='identifier',
            field=models.CharField(help_text='IRI Identifier', max_length=200),
        ),
    ]
