# Generated by Django 3.0.5 on 2020-04-17 15:23

from django.db import migrations, models
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('core', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('In work', 'In work'), ('Awaiting review', 'Awaiting review'), ('In review', 'In review'), ('Completed', 'Completed')], default='In work', max_length=15)),
                ('properties', jsonfield.fields.JSONField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('analyst', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('aoi', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='features', to='core.AOI')),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.Job')),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.Project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maps.FeatureType')),
            ],
            options={
                'ordering': ('-updated_at', 'aoi'),
            },
        ),
    ]
