# Generated by Django 3.0.7 on 2020-06-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200623_1333'),
        ('maps', '0002_auto_20200417_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='ontology_reference',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='feature',
            name='aoi',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.AOI'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='job',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Job'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='image_format',
            field=models.CharField(blank=True, choices=[('image/png', 'image/png'), ('image/png8', 'image/png8'), ('image/png24', 'image/png24'), ('image/jpeg', 'image/jpeg'), ('image/gif', 'image/gif'), ('image/tiff', 'image/tiff'), ('image/tiff8', 'image/tiff8'), ('image/geotiff', 'image/geotiff'), ('image/geotiff8', 'image/geotiff8'), ('image/svg', 'image/svg'), ('image/vnd.jpeg-png', 'image/vnd.jpeg-png'), ('rss', 'rss'), ('kml', 'kml'), ('kmz', 'kmz'), ('json', 'json'), ('png', 'png'), ('png8', 'png8'), ('png24', 'png24'), ('jpeg', 'jpeg'), ('jpg', 'jpg'), ('gif', 'gif'), ('tiff', 'tiff'), ('tiff8', 'tiff8'), ('geotiff', 'geotiff'), ('geotiff8', 'geotiff8'), ('svg', 'svg')], help_text='The MIME type of the image format to use for tiles on WMS layers (image/png, image/jpeg image/gif...). Double check that the server exposes this exactly - some servers push png instead of image/png.', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.CharField(choices=[('WMS', 'WMS'), ('WFS', 'WFS'), ('WCS', 'WCS'), ('KML', 'KML'), ('GeoRSS', 'GeoRSS'), ('ESRI Identifiable MapServer', 'ESRI Identifiable MapServer'), ('ESRI Tiled Map Service', 'ESRI Tiled Map Service'), ('ESRI Dynamic Map Layer', 'ESRI Dynamic Map Layer'), ('ESRI Feature Layer', 'ESRI Feature Layer'), ('ESRI Shapefile', 'ESRI Shapefile'), ('GeoJSON', 'GeoJSON'), ('ESRI Clustered Feature Layer', 'ESRI Clustered Feature Layer'), ('GPX', 'GPX'), ('WMTS', 'WMTS'), ('Social Networking Link', 'Social Networking Link'), ('Web Data Link', 'Web Data Link'), ('Bing', 'Bing'), ('Google Maps', 'Google Maps'), ('Yandex', 'Yandex'), ('Leaflet Tile Layer', 'Leaflet Tile Layer'), ('MediaQ', 'MediaQ'), ('NWS Weather Alerts', 'NWS Weather Alerts'), ('OpenSensorHub', 'OpenSensorHub'), ('MAGE', 'MAGE'), ('MAGE Users', 'MAGE Users')], help_text='Type of service for the new layer.', max_length=75),
        ),
    ]
