# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='color',
            field=models.CharField(default=b'#cf0101', max_length=16, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
